global using Microsoft.Maui.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.DependencyInjection;
global using System.Collections;
global using System.ComponentModel;
global using System.Runtime.CompilerServices;
global using System.Windows;
global using System.Windows.Input;
global using System.Windows.Markup;